apiVersion: batch/v1
kind: Job
metadata:
  name: batch
  namespace: job
spec:
  completions: 3
  parallelism: 1
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: batch
        image: alpine
        command: ['echo', 'Hello World']