---
apiVersion: v1
kind: Namespace
metadata:
  name: lab4bis
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: lab4bis
data:
  # property-like keys; each key maps to a simple value
  nginx-conf: "nginx-conf"

  # file-like keys
  nginx-conf: |
    server {
        location / {
            root /data/www;
        }
        location /images/ {
            root /data; }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: lab4bis
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: "/etc/nginx.conf"
          readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf