---
apiVersion: v1
kind: Namespace
metadata:
  name: lab4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  namespace: lab4
  labels:
    app: web
spec:
  replicas: 4
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: lab4
spec:
  selector:
    app: web
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: debug
  namespace: lab4
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: alpine
        image: alpine
        command:
        - "bin/sh"
        - "-c"
        - "echo 'Hello! I am running on '$debug; while true; do sleep 300s ; done;"