apiVersion: v1
kind: Namespace
metadata:
  name: lab2

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  namespace: lab2
spec:
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:bullseye
        ports:
        - containerPort: 80
      nodeSelector:
        purpose: web

---

apiVersion: v1
kind: Service
metadata:
  name: nodeport-httpd
  namespace: lab2
spec:
  type: NodePort
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 30000