---
apiVersion: v1
kind: Namespace
metadata:
  name: lab3
---
apiVersion: v1
kind: Service
metadata:
  name: s1
  namespace: lab3
spec:
  selector:
      app1: web
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
---
apiVersion: v1
kind: Pod
metadata:
  name: web1
  namespace: lab3
  labels:
    app1: web
spec:
  containers:
  - image: nginx
    name: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: web2
  namespace: lab3
  labels:
    app1: web
spec:
  containers:
  - image: httpd
    name: httpd
---
apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: lab3
spec:
  containers:
  - image: debian
    name: debian
    command:
    - "bin/sh"
    - "-c"
    - "echo 'Hello! I am running on '$debug; while true; do sleep 300s ; done;"
---
apiVersion: v1
kind: Service
metadata:
  name: s2
  namespace: lab3
spec:
  selector:
    app2: web
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 30000
---
apiVersion: v1
kind: Pod
metadata:
  name: web3
  namespace: lab3
  labels:
    app2: web
spec:
  containers:
  - image: nginx
    name: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: web4
  namespace: lab3
  labels:
    app2: web
spec:
  containers:
  - image: httpd
    name: httpd