---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: web
  namespace: lab6
  labels:
    app: web
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/samir/Documents/sdv_kubernetes/Lab6/web