apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web
  namespace: lab6
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      app: web