apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: lab6
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        ports:
        - containerPort: 80
        image: nginx
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: web
      volumes:
        - name: web
          persistentVolumeClaim:
            claimName: web